[package]
name = "cron_clock"
version = "0.6.1"
authors = ["binchengZhao <binchengZhao@outlook.com>"]
repository = "https://github.com/BinChengZhao/cron"
documentation = "https://docs.rs/cron"
readme = "README.md"
description = "A cron expression parser and schedule explorer. I forked by zslayton.Please correct me if there is anything wrong."
keywords = [ "cron", "schedule", "repeat", "periodic", "time" ]
license = "MIT"

[lib]
name = "cron"

[dependencies]
chrono = "~0.4"
nom = "~4.1"
error-chain="~0.10.0"
